name: system-info
on:
  workflow_call:

jobs:
  system-info:
    name: "System Information"
    steps:
      - name: "Show GitHub Action event.head_commit variable"
        env:
          CONTENT: "${{ toJSON(github.event.head_commit) }}"
        run: echo "$CONTENT"
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
          exit 0
