name: build-cachelib-rockylinux-9.0
on:
#   push:
  schedule:
     - cron:  '30 5 * * 1,4'
jobs:
  build-cachelib-rockylinux-9:
    name: "RockyLinux-9.0 - Build CacheLib with all dependencies"
    runs-on: ubuntu-latest
    # Docker container image name
    container: "rockylinux:9.0"
    steps:
      - name: "Show Head Commit"
        env:
          CONTENT: ${{ toJSON(github.event.head_commit) }}
        run: echo "$CONTENT"
      - name: "update packages"
        # stock centos has a problem with CMAKE, fails with:
        #  "cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd"
        # updating solves it
        run: dnf update -y
      - name: "install sudo,git"
        run: dnf install -y sudo git cmake gcc procps
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === nproc ===
          nproc || true
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === gcc -v ===
          gcc -v
      - name: "checkout sources"
        uses: actions/checkout@v2
      - name: "Install Prerequisites"
        run: ./contrib/build.sh -S -B
      - name: "Test: update-submodules"
        run: ./contrib/update-submodules.sh
      - name: "Install dependency: zstd"
        run: ./contrib/build-package.sh -j -v -i zstd
      - name: "Install dependency: googleflags"
        run: ./contrib/build-package.sh -j -v -i googleflags
      - name: "Install dependency: googlelog"
        run: ./contrib/build-package.sh -j -v -i googlelog
      - name: "Install dependency: googletest"
        run: ./contrib/build-package.sh -j -v -i googletest
      - name: "Install dependency: sparsemap"
        run: ./contrib/build-package.sh -j -v -i sparsemap
      - name: "Install dependency: fmt"
        run: ./contrib/build-package.sh -j -v -i fmt
      - name: "Install dependency: folly"
        run: |
          # see: https://aur.archlinux.org/packages/folly#comment-862543
          sed -i '$aset(LIBDWARF_INCLUDE_DIRS "/usr/include/libdwarf-0")' cachelib/external/folly/CMake/FindLibDwarf.cmake
          ./contrib/build-package.sh -S -j -v -i folly
      - name: "Install dependency: fizz"
        run: ./contrib/build-package.sh -j -v -i fizz
      - name: "Install dependency: wangle"
        run: ./contrib/build-package.sh -j -v -i wangle
      - name: "Install dependency: fbthrift"
        run: ./contrib/build-package.sh -j -v -i fbthrift
      - name: "build CacheLib"
        # Build cachelib in debug mode (-d) and with all tests (-t)
        run: ./contrib/build-package.sh -j -v -i -d -t cachelib
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cachelib-cmake-logs
          path: |
            build-cachelib/CMakeFiles/*.log
            build-cachelib/CMakeCache.txt
            build-cachelib/Makefile
            build-cachelib/**/Makefile
          if-no-files-found: warn
          retention-days: 1

